# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 15:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
