# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0002_auto_20180522_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='identificador',
            field=models.IntegerField(default=0),
        ),
    ]
