# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0002_estudiante_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='monitor',
            field=models.BooleanField(default=False),
        ),
    ]
