# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 16:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0007_auto_20180608_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='identificacion',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
